SELECT 
  c.CUSTOMER_ID, 
  c.FIRST_NAME, 
  c.LAST_NAME, 
  EXTRACT(
    YEAR 
    FROM 
      b.BOOKING_DATE
  ) AS BOOKING_YEAR, 
  SUM(b.TOTAL_PRICE) AS TOTAL_BOOKING_AMOUNT, 
  l.CITY 
FROM 
  customers c 
  JOIN bookings b ON c.CUSTOMER_ID = b.CUSTOMER_ID 
  JOIN HOTELS h ON b.HOTEL_ID = h.HOTEL_ID 
  JOIN LOCATION l ON h.LOCATION_ID = l.LOCATION_ID 
GROUP BY 
  c.CUSTOMER_ID, 
  c.FIRST_NAME, 
  c.LAST_NAME, 
  EXTRACT(
    YEAR 
    FROM 
      b.BOOKING_DATE
  ), 
  l.CITY 
ORDER BY TOTAL_BOOKING_AMOUNT DESC
