CREATE MATERIALIZED VIEW mv_total_bookings_by_location BUILD IMMEDIATE REFRESH ON DEMAND AS 
SELECT 
  h.HOTEL_ID, 
  h.HOTEL_NAME, 
  l.CITY, 
  l.STATE, 
  COUNT(b.BOOKING_ID) AS TOTAL_BOOKINGS 
FROM 
  HOTELS h 
  JOIN LOCATION l ON h.LOCATION_ID = l.LOCATION_ID 
  LEFT JOIN BOOKINGS b ON h.HOTEL_ID = b.HOTEL_ID 
GROUP BY 
  h.HOTEL_ID, 
  h.HOTEL_NAME, 
  l.CITY,   l.STATE;
